### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by russelltaylor05** [robinjoseph08/pokedextracker.com#105]
How do I install my pokemon?

**Comment by robinjoseph08** [comment]
Hey @russelltaylor05,

Sorry for the confusion you're having. I think there may have been a bit of a misunderstanding. Pokédex Tracker is an online service that you use to easily keep track of your progress as you attempt to complete a [Living Dex](http://bulbapedia.bulbagarden.net/wiki/Living_Pok%C3%A9dex). This application is primarily geared for tracking the Pokémon in Generation VI (X, Y, Omega Ruby, or Alpha Sapphire).

Because of the online nature of this website, there is actually no need to install any additional software or Pokémon onto your own computer. All you have to do is visit the URL in your browser, sign in, and start marking them as caught as you catch them in your game!

Hope that clears things up for you! Let us know if you have any other questions! Happy tracking!

Cheers,
Robin

**Comment by russelltaylor05** [comment]
I dunno, that sounds like a lot of work, can I just get a refund instead?
