### ISSUE TITLE
Translating

### ISSUE THREAD

**Issue by chagara** [robinjoseph08/pokedextracker.com#169]
Hello,

Have you guys considered translating the pokedex into different languages?

**Comment by robinjoseph08** [comment]
Yeah we actually have it as [an issue](https://github.com/robinjoseph08/pokedextracker.com/issues/146)! Since all of the pokemon names in the different languages are available, it should be pretty straightforward.

I'm gonna close this issue since we already have that other one to keep track of it, but thanks for the feature request! We always like hearing what our users want!
