### ISSUE TITLE
Rethink hover to see info UX

### ISSUE THREAD

**Issue by ami** [robinjoseph08/pokedextracker.com#20]
### why
- if i'm in the middle of a cell and i want to scroll on the info bar, it's essentially impossible

### thoughts
- get rid of hover? add another click instead?

**Comment by ami** [comment]
@robinjoseph08 a couple ideas i have below. lemme know what you think!

![slack for ios upload 1](https://cloud.githubusercontent.com/assets/5498072/14009373/770ef766-f148-11e5-88f0-fed7643db649.jpg)

1) **split on hover:** on hover, split the panel in half. one half is the button to show `info`, one half is the button to mark as `captured`

**pros**:
- we get to keep the existing look of the box view
- it's very clear on hover the two things you can do

**cons**:
- what do we do AFTER a button is clicked? animation for marking as `captured`?

2) **info btn:** button across the bottom of each panel to open `info`, replacing the space that `national_id` currently takes up. the rest of the box remains as the way to mark as `captured`

**pros**:
- no hover action, so it's a simpler experience

**cons**:
- will so many "info" buttons on the main box view look messy?
- we lose information about the pokemon (`national_id`)

3) **info btn on hover:** show a button on hover in the corner of the panel to open `info`. the rest of the box remains as the way to mark as `captured`

**pros**:
- we get to keep the existing look of the box view
- still lots of room to mark as captured

**cons**:
- does this draw too much attention to the "info" button and not enough to the action of marking as `captured`? perhaps we'd need to add an additional hover style to the rest of the box to show that that part of the box is clickable too.

**Comment by robinjoseph08** [comment]
these are some good ideas :+1: i dont know which one i prefer just yet, but ive got a few comments for them:

- will the info panel still default to bulbasaur for all of these?
- for 1, yeah it's a bit weird to think about what happens on click... maybe the background of the captured side turns yellow and then when you hover off of it, you see the whole box is yellow? i don't think that's ideal
- at first glance i really like 2, but i think the number is actually pretty important info (since everything is organized by this number), so it shouldn't be removed. also a whole 30-pokemon box of these with little "info" bars might break the nice clean look we've got going on and i like that nice clean look
- i'm concerned for how difficult it would be to click the info button for 2 and 3. is it too small? i liked how easy it was to show the info with our initial hover idea, so ideally, it stays as easy to show the info. i think it might be fine, but it's just something i'm slightly worried about
- i would prefer that the image always be visible (so that's a point in favor of 2 and 3)
- since the info now changes on click, is it necessary to visually show which pokemon is currently "selected"?

after typing this all out, i think im leaning toward 3. but you do pose a good point about the focus on info button instead of the capture toggle. did you have any hover styles in mind that we can do to the captured part of it?

**Comment by ami** [comment]
- yes, but we could also add an empty state

after writing everything out I ended up leaning towards 3 too. a thicker yellow border or maybe a 50%yellow bg could work as the hover? I'd have to see how it all looks together

**Comment by ami** [comment]
oh I missed one:

- I don't think a "selected" state is as necessary as a hover. It's pretty clear from the info panel which Pokemon is selected

**Comment by robinjoseph08** [comment]
kewl I can dig it. I'm liking the 50% idea, but yeah, let's try them out :+1:

and yeah, that makes sense that a selected state isn't necessary
